### ISSUE TITLE
Error during autoconf

### ISSUE THREAD

**Issue by vaibhavkhanduja** [yoe/nbd#26]
While running autoconf on ubuntu I get following errors, can you tell me what pkg i am missing, I am on ubuntu 14.04

configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:9: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:154: error: possibly undefined macro: AM_PATH_GLIB_2_0
configure.ac:160: error: possibly undefined macro: AM_CONDITIONAL

**Comment by yoe** [comment]
It's easiest to just use the Ubuntu packages, but if you must: automake and glib (you could've figured that out by just reading the names of the missing macros, though...)
