### ISSUE TITLE
NBD devices don't have ID_FS_TYPE

### ISSUE THREAD

**Issue by alkisg** [yoe/nbd#36]
This bug is causing 30 or 10 seconds delay when NBD clients boot, because initramfs-tools calls `wait-for-root /dev/nbd0 <10 or 30 second delay>`, and wait-for-root doesn't see ID_FS_TYPE so it only returns after the timeout.

It's been reported against udev in: https://bugs.freedesktop.org/show_bug.cgi?id=62565
...where it was marked as not a bug in udev, and the necessary changes for NBD were suggested:
> removing the blacklist could only happen if the nbd kernel side is changed to send out events
like loop, dm, md are doing it

It's also been reported against nbd and initramfs in Ubuntu 5 years ago:
https://bugs.launchpad.net/ubuntu/+source/nbd/+bug/696435

In LTSP we're currently using this as a workaround:
http://bazaar.launchpad.net/~ltsp-upstream/ltsp/ltsp-trunk/view/head:/client/Debian/share/initramfs-tools/scripts/local-top/nbd_ltsp

**Comment by yoe** [comment]
The change events are being worked on; see systemd/systemd#2422 and the LKML reference there for details. Closing, as this is a kernel issue and this project is about the user space tools, not the kernel module.

**Comment by alkisg** [comment]
Thank you Wouter, I filed it here mainly in case you wanted to include the LTSP workaround in the initramfs-tools/scripts/local-top/nbd user space script, but if it's going to be fixed soonish in the kernel side then there's no point to.
